[package]
name = "gimoji"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
crossterm = "0.26.1"
dirs = "5.0.1"
ureq = { version = "2.6.2", default-features = false, features = ["tls"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tui = "0.19.0"
