[package]
name = "gimoji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.0"
crossterm = "0.26.1"
dirs = "5.0.1"
serde_json = "1.0.96"
tui = "0.19.0"
